---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-app
spec:
  service_type: nodeport
  extra_settings:
  - setting: CSRF_TRUSTED_ORIGINS
    value:
      - https://awx.chaitu.net
